### ISSUE TITLE
Need to upgrade Nodejs and python version for lambda function

### ISSUE THREAD

**Issue by AungMy0** [aws-samples/amazon-ivs-ugc-platform-web-demo#20]
nodejs14.x and  python3.7 are no longer supported for creating or updating AWS Lambda functions.
function Names 
- BucketNotificationsHandler
- LogRetention
- CustomS3AutoDeleteObjectsCustomResourceProviderHandler

**Comment by Goateater94** [comment]
I have the same problem

**Comment by sacha-rk** [comment]
Do you know how to upgrade nodejs14.x to  nodejs20.x?
Can't deploy the app: Resource handler returned message: "The runtime parameter of nodejs14.x is no longer supported for creating or updating AWS Lambda functions.

**Comment by andreido** [comment]
Hello all! Thanks for reporting this issue.

We have recently updated this demo (#21) to address the outdated AWS Lambda runtimes mentioned in this issue, as well as other dependency upgrades. Please pull the latest changes from this repository and try deploying the CDK stack once again.

Thanks!
