### ISSUE TITLE
Missing required filter, one of: isLive

### ISSUE THREAD

**Issue by sacha-rk** [aws-samples/amazon-ivs-ugc-platform-web-demo#30]
Hi, 
Here is the request I made:
curl --location 'https://xxxxxxxx.cloudfront.net/channels?isLive=true' \
--header 'accept: */*' \
--header 'content-type: application/json' \

The response:
{
    "__type": "BadRequestException",
    "message": "Missing required filter, one of: isLive"
}

Any Idea?

**Comment by andreido** [comment]
Hello @sacha-rk! Sorry to hear you are experiencing this error.

We have investigated the issue you described and have not been able to reproduce the error you are experiencing. Can you please ensure that you have deployed the most recent changes in the repository and that your dependencies are up-to-date, then try running the cURL command below (note that `isLive` is case-sensitive):

```
curl --location "https://xxxxxxxxxxxx.cloudfront.net/channels?isLive=true" \
--header "Accept: */*" \
--header "Content-Type: application/json"
```

If the issue continues to persist, please provide us with the following additional information:
* The region to which you have deployed the CDK stack
* The version of the `fastify` npm package that you are running
* Any CloudWatch logs that are relevant to the failed request
