### ISSUE TITLE
Docker push fails, 400 Bad Request

### ISSUE THREAD

**Issue by auctionwebsites** [aws-samples/amazon-ivs-ugc-platform-web-demo#39]
The command make app fails with the following:

fail: docker push XXX exited with error code 1: failed commit on ref "XXX": unexpected status from PUT request to XXX: 400 Bad Request

**Comment by slee-aws** [comment]
@auctionwebsites Hello! Sorry to hear you're having this issue. I am not able to reproduce the issue you are seeing. Could you confirm if you have docker running locally?

**Comment by auctionwebsites** [comment]
> @auctionwebsites Hello! Sorry to hear you're having this issue. I am not able to reproduce the issue you are seeing. Could you confirm if you have docker running locally?

Yes, I can confirm Docker was running locally (Mac M1)

**Comment by mboulin** [comment]
@auctionwebsites while we are not able to reproduce your issue, here is a list of possible causes to your 400 issue:

- Registry limitation
  - Size limits for images
    - Run `docker system prune -a` to remove all unused containers, networks and images (https://docs.docker.com/reference/cli/docker/system/prune/)
  - Exceeded ECR repository or image quotas for the AWS account
    - Please refer to the [Amazon ECR service quotas](https://docs.aws.amazon.com/AmazonECR/latest/userguide/service-quotas.html#:~:text=To%20view%20Amazon%20ECR%20service%20quotas%20(AWS%20Management%20Console)&text=From%20the%20AWS%20services%20list,the%20quota%20value%20is%20adjustable.) document
- Authentication issues
  - Expired or invalid AWS credentials
  - Insufficient IAM permissions for ECR operations
    - Refer to this [document](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_users_change-permissions.html) to check and change permissions for an IAM user
- Network issue
  - ISP hiccup
  - VPN or proxy causing issues
- AWS account limits: Account may be reached the limit for the number of repositories or images
- More help:
  - Please refer to the [CannotPullContainer task errors in Amazon ECS](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_cannot_pull_image.html) document for more 
information
  - When running the cdk deploy command, add the debug option `cdk deploy –debug` to get a more detailed log (https://docs.aws.amazon.com/cdk/v2/guide/cli.html#cli-init)
  
If your issue persist, consider asking on [AWS re:Post](https://repost.aws/).
